name: publish-nuget

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
  push:
    branches: [ master ]

jobs:
  publish:
    name: build, test, pack & publish
    runs-on: ubuntu-latest
    environment: nuget-publish # Configured in Settings > Environments
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore Npoi.Mapper/Npoi.Mapper.sln
      - name: Build
        run: dotnet build --no-restore Npoi.Mapper/Npoi.Mapper.sln
      - name: Test
        run: dotnet test --framework net6.0 --no-build --verbosity normal Npoi.Mapper/Npoi.Mapper.sln

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Npoi.Mapper/src/Npoi.Mapper/Npoi.Mapper.csproj

          # Platform target to compile (default is empty/AnyCPU)
          # BUILD_PLATFORM: x64

          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: Npoi.Mapper

          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 1.0.0

          # Flag to toggle git tagging, enabled by default
          # Do not push tags, we use tag to trigger nuget publish.
          TAG_COMMIT: false

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          # NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
